image:
- Visual Studio 2017
- Ubuntu
stack: python 3.6, python 3.7
version: '{branch}-{build}'
branches:
  only:
  - default
environment:
  matrix:
  - WIN_PYTHON: C:\\Python36
    LNX_PYTHON: 3.6

  - WIN_PYTHON: C:\\Python37
    LNX_PYTHON: 3.7

  exclude:
    image: Ubuntu
    LNX_PYTHON: 3.7
build: off
install:
- cmd: '%WIN_PYTHON%\\python.exe -m pip install typing_extensions'
- sh: '~/venv$LNX_PYTHON*/bin/python3 -m pip install typing_extensions'
test_script:
- cmd: '%WIN_PYTHON%\\python.exe -m unittest -v'
- sh: '~/venv$LNX_PYTHON*/bin/python3 -m unittest -v'
notifications:
- provider: Email
  to:
  - ronaldoussoren@mac.com
  subject: 'appveyor: objectgraph'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false

